const colors = require("tailwindcss/colors");
const magento = {
    header: '#5f564f',
    color: '#514943',
    background: {
        DEFAULT: '#f5f5f5',
        hover: '#dbdbdb'
    }
}
module.exports = {
    corePlugins: {
        preflight: false,
    },
    purge: {
        content: [
            "../../../../../../../vendor/hyva-themes/module-magento2-admin/view/adminhtml/templates/**/*.phtml",
            "../../../../../../../vendor/hyva-themes/magento2-hyva-widgets/src/view/adminhtml/templates/**/*.phtml",
            "../../../../../../../vendor/hyva-themes/magento2-theme-module/src/view/adminhtml/templates/**/*.phtml",
            "../../**/*.phtml",
            "../../../../../../code/GardenLawn/**/view/adminhtml/templates/**/*.phtml"
        ],
        safelist: [
            'text-3xl',
            'text-2xl',
            'text-xl',
            'text-lg',
            'text-base',
            'text-sm',
            'text-xs',
            'font-bold',
            'font-semibold',
            'font-medium',
            'font-normal',
            'font-light',
            'text-left',
            'text-center',
            'text-right',
            'text-justify',
            'uppercase',
            'lowercase',
            'capitalize',
            'italic',
            'not-italic',
            'underline',
            'line-through',
            'no-underline',
            'break-normal',
            'break-words',
            'break-all',
            'truncate',
            'leading-none',
            'leading-tight',
            'leading-snug',
            'leading-normal',
            'leading-relaxed',
            'leading-loose',
            'list-none',
            'list-disc',
            'list-decimal',
            'list-inside',
            'list-outside',
            'block',
            'inline-block',
            'inline',
            'flex',
            'inline-flex',
            'table',
            'table-row',
            'table-cell',
            'hidden',
            'static',
            'fixed',
            'absolute',
            'relative',
            'sticky',
            'visible',
            'invisible',
            'flex-row',
            'flex-row-reverse',
            'flex-col',
            'flex-col-reverse',
            'flex-wrap',
            'flex-wrap-reverse',
            'flex-nowrap',
            'items-start',
            'items-end',
            'items-center',
            'items-baseline',
            'items-stretch',
            'justify-start',
            'justify-end',
            'justify-center',
            'justify-between',
            'justify-around',
            'justify-evenly',
            'content-center',
            'content-start',
            'content-end',
            'content-between',
            'content-around',
            'self-auto',
            'self-start',
            'self-end',
            'self-center',
            'self-stretch',
            'order-first',
            'order-last',
            'order-none',
            'order-1',
            'order-2',
            'order-3',
            'order-4',
            'order-5',
            'order-6',
            'order-7',
            'order-8',
            'order-9',
            'order-10',
            'order-11',
            'order-12',
            'w-full',
            'w-screen',
            'w-auto',
            'h-full',
            'h-screen',
            'h-auto',
            'm-0',
            'm-1',
            'm-2',
            'm-3',
            'm-4',
            'm-5',
            'm-6',
            'm-8',
            'm-10',
            'm-12',
            'm-16',
            'm-20',
            'm-24',
            'm-32',
            'm-40',
            'm-48',
            'm-56',
            'm-64',
            'm-auto',
            'p-0',
            'p-1',
            'p-2',
            'p-3',
            'p-4',
            'p-5',
            'p-6',
            'p-8',
            'p-10',
            'p-12',
            'p-16',
            'p-20',
            'p-24',
            'p-32',
            'p-40',
            'p-48',
            'p-56',
            'p-64',
            'border',
            'border-0',
            'border-2',
            'border-4',
            'border-8',
            'border-solid',
            'border-dashed',
            'border-dotted',
            'border-double',
            'border-none',
            'rounded-none',
            'rounded-sm',
            'rounded',
            'rounded-md',
            'rounded-lg',
            'rounded-xl',
            'rounded-2xl',
            'rounded-3xl',
            'rounded-full',
            'shadow-sm',
            'shadow',
            'shadow-md',
            'shadow-lg',
            'shadow-xl',
            'shadow-2xl',
            'shadow-inner',
            'shadow-none',
            'opacity-0',
            'opacity-5',
            'opacity-10',
            'opacity-20',
            'opacity-25',
            'opacity-30',
            'opacity-40',
            'opacity-50',
            'opacity-60',
            'opacity-70',
            'opacity-75',
            'opacity-80',
            'opacity-90',
            'opacity-95',
            'opacity-100',
            'cursor-auto',
            'cursor-default',
            'cursor-pointer',
            'cursor-wait',
            'cursor-text',
            'cursor-move',
            'cursor-help',
            'cursor-not-allowed',
            'select-none',
            'select-text',
            'select-all',
            'select-auto',
            'sr-only',
            'not-sr-only',
        ]
    },
    darkMode: false,
    theme: {
        fontSize: {
            xs: ['0.75em', { lineHeight: '1em' }],
            sm: ['0.875em', { lineHeight: '1.25em' }],
            base: ['1em', { lineHeight: '1.5em' }],
            lg: ['1.125em', { lineHeight: '1.75em' }],
            xl: ['1.25em', { lineHeight: '1.75em' }],
            '2xl': ['1.5em', { lineHeight: '2em' }],
            '3xl': ['1.875em', { lineHeight: '2.25em' }],
            '4xl': ['2.25em', { lineHeight: '2.5em' }],
            '5xl': ['3em', { lineHeight: '1' }],
            '6xl': ['3.75em', { lineHeight: '1' }],
            '7xl': ['4.5em', { lineHeight: '1' }],
            '8xl': ['6em', { lineHeight: '1' }],
            '9xl': ['8em', { lineHeight: '1' }],
        },
        colors: {
            gray: colors.warmGray,
        },
        textColor: {
            white: colors.white,
            black: colors.black,
            gray: colors.gray,
            primary: {
                lighter: colors.gray["700"],
                DEFAULT: magento.color,
                darker: colors.gray["900"],
            },
            secondary: {
                lighter: colors.gray["400"],
                DEFAULT: colors.gray["500"],
                darker: colors.gray["600"],
            },
        },
        backgroundColor: {
            white: colors.white,
            gray: colors.gray,
            primary: {
                lighter: colors.gray["200"],
                DEFAULT: magento.background.DEFAULT,
                darker: magento.background.hover,
            },
            secondary: {
                lighter: colors.gray["100"],
                DEFAULT: colors.gray["200"],
                darker: colors.gray["300"],
            },
            container: {
                lighter: colors.white,
                DEFAULT: colors.gray["100"],
                darker: colors.gray["200"],
                header: magento.color,
                hover: magento.header
            },
        },
        borderColor: {
            gray: colors.gray,
            transparent: colors.transparent,
            primary: {
                lighter: colors.gray["300"],
                DEFAULT: colors.gray["500"],
                darker: magento.header,
            },
            secondary: {
                lighter: colors.gray["100"],
                DEFAULT: colors.gray["200"],
                darker: colors.gray["300"],
            },
            container: {
                lighter: colors.gray["100"],
                DEFAULT: colors.gray["200"],
                darker: colors.gray["300"],
            },
        },
    },
    variants: {
        extend: {},
    },
    plugins: [
        require("@tailwindcss/forms")({strategy: 'class'})
    ],
};
